export { default as CommunityPage } from "./Community.jsx";
export { default as CreatePostPage } from "./CreatePost.jsx";
export { default as HomePage } from "./Home.jsx";
export { default as LoginPage } from "./Login.jsx";
export { default as PostPage } from "./PostPage.jsx";
export { default as RegisterPage } from "./Register.jsx";
export { default as UserPage } from "./User.jsx";
export { default as UserCommentsPage } from "./UserComments.jsx";
export { default as UserUpvotesPage } from "./UserUpvotes.jsx";
